name: Build and deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions 
        uses: actions/checkout@main

      - name: Login to Azure CR
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure CR
        uses: azure/docker-login@v1
        with:
            login-server: ${{ secrets.LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Create .env file
        run: |
          touch .env 
          echo DB_URI = ${{ secrets.DB_URI }} >> .env
          echo PORT = ${{ secrets.PORT }} >> .env 
        
      - name: Push docker image
        run: |
          docker build . -t ${{ secrets.LOGIN_SERVER }}/api-cicd:${{ github.sha }}
          docker push ${{ secrets.LOGIN_SERVER }}/api-cicd:${{ github.sha }}

      - name: Deploy to Azure App Service 
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'api-cicd'
          images: '${{ secrets.LOGIN_SERVER }}/api-cicd:${{ github.sha }}'

      - name: Logout from Azure Service
        run: |
          az logout